export const FEATURED = {
  id: "featured-ai-short",
  title: "Where Do The Strays Go — An AI Short",
  category: "Featured Film",
  provider: "youtube",
  video_id: "WmtGrkCIS-M",
  source_url: "https://youtu.be/WmtGrkCIS-M",
  thumbnail: "https://img.youtube.com/vi/WmtGrkCIS-M/hqdefault.jpg",
};

export const FILMS = [
  {
    id: "film-HAWMCxhyXmk",
    title: "PLUM GOODNESS",
    provider: "youtube",
    video_id: "HAWMCxhyXmk",
    source_url: "https://youtu.be/HAWMCxhyXmk?si=OrZSYb-2NSFSYsbB",
    thumbnail: "https://img.youtube.com/vi/HAWMCxhyXmk/hqdefault.jpg",
    order: 0,
  },
  {
    id: "film-oSK32tZ-sA0",
    title: "FREECHARGE UPI",
    provider: "youtube",
    video_id: "oSK32tZ-sA0",
    source_url: "https://youtu.be/oSK32tZ-sA0?si=mGtaXgt2FGo90TlZ",
    thumbnail: "https://img.youtube.com/vi/oSK32tZ-sA0/hqdefault.jpg",
    order: 1,
  },
  {
    id: "film-y0iIze2DRpY",
    title: "STAR PLUS _NAYI SOCH MS DHONI",
    provider: "youtube",
    video_id: "y0iIze2DRpY",
    source_url: "https://youtu.be/y0iIze2DRpY?si=ybizu2-WBu_p2m3a",
    thumbnail: "https://img.youtube.com/vi/y0iIze2DRpY/hqdefault.jpg",
    order: 2,
  },
  {
    id: "film-jnGAceCdqiI",
    title: "JOY_BEAUTIFUL BY NATURE",
    provider: "youtube",
    video_id: "jnGAceCdqiI",
    source_url: "https://youtu.be/jnGAceCdqiI?si=Pssk6xnsEsBI3Ehr",
    thumbnail: "https://img.youtube.com/vi/jnGAceCdqiI/hqdefault.jpg",
    order: 3,
  },
  {
    id: "film-PXu954CK08c",
    title: "FREECHARGE_ PAYLATER",
    provider: "youtube",
    video_id: "PXu954CK08c",
    source_url: "https://youtu.be/PXu954CK08c?si=QNHigZFBr3-Zi7J-",
    thumbnail: "https://img.youtube.com/vi/PXu954CK08c/hqdefault.jpg",
    order: 4,
  },
  {
    id: "film-XHK0CIY3Cqg",
    title: "SHELL HELIX _MECHANICURE (TAMIL)",
    provider: "youtube",
    video_id: "XHK0CIY3Cqg",
    source_url: "https://youtu.be/XHK0CIY3Cqg?si=mqCNFShR7OWiBvwA",
    thumbnail: "https://img.youtube.com/vi/XHK0CIY3Cqg/hqdefault.jpg",
    order: 5,
  },
  {
    id: "film-XlKUc22z-y4",
    title: "YARDELY ESSENTIALS_MALAYALAM",
    provider: "youtube",
    video_id: "XlKUc22z-y4",
    source_url: "https://youtu.be/XlKUc22z-y4?si=mYj4VpxtLZZsqnns",
    thumbnail: "https://img.youtube.com/vi/XlKUc22z-y4/hqdefault.jpg",
    order: 6,
  },
  {
    id: "film-GrOLkAYEWAw",
    title: "NIVEA SOFT_TAPSEE",
    provider: "youtube",
    video_id: "GrOLkAYEWAw",
    source_url: "https://youtu.be/GrOLkAYEWAw?si=FzVuRdlXHXAfqt6y",
    thumbnail: "https://img.youtube.com/vi/GrOLkAYEWAw/hqdefault.jpg",
    order: 7,
  },
  {
    id: "film-napilJZyFZA",
    title: "JOY_BEAUTIFUL BY NATURE_PRINCESS",
    provider: "youtube",
    video_id: "napilJZyFZA",
    source_url: "https://youtu.be/napilJZyFZA?si=JFPhVGSkZ0JXgljn",
    thumbnail: "https://img.youtube.com/vi/napilJZyFZA/hqdefault.jpg",
    order: 8,
  },
  {
    id: "film--dnNxPZLMCw",
    title: "SHELL ADVANCE_THE RIDE",
    provider: "youtube",
    video_id: "-dnNxPZLMCw",
    source_url: "https://youtu.be/-dnNxPZLMCw?si=vQTrUszT4K0Fy60G",
    thumbnail: "https://img.youtube.com/vi/-dnNxPZLMCw/hqdefault.jpg",
    order: 9,
  },
  {
    id: "film-QSLOmSt3Mro",
    title: "YAMAHA RAY ZR",
    provider: "youtube",
    video_id: "QSLOmSt3Mro",
    source_url: "https://youtu.be/QSLOmSt3Mro?si=M4_TLrI3qCCbmgkQ",
    thumbnail: "https://img.youtube.com/vi/QSLOmSt3Mro/hqdefault.jpg",
    order: 10,
  },
  {
    id: "film-fMa4aq66v-w",
    title: "ROYAL ENFIELD_METEOR",
    provider: "youtube",
    video_id: "fMa4aq66v-w",
    source_url: "https://youtu.be/fMa4aq66v-w?si=rS9RnN779VpAGSjI",
    thumbnail: "https://img.youtube.com/vi/fMa4aq66v-w/hqdefault.jpg",
    order: 11,
  },
  {
    id: "film-VMtPfjakgHE",
    title: "STARPLUS_NAYISOCH VIRAT",
    provider: "youtube",
    video_id: "VMtPfjakgHE",
    source_url: "https://youtu.be/VMtPfjakgHE?si=6Whg6Ujog9JYVKLM",
    thumbnail: "https://img.youtube.com/vi/VMtPfjakgHE/hqdefault.jpg",
    order: 12,
  },
  {
    id: "film-RmF4DKhPaV4",
    title: "TVS APACHE RTR 200",
    provider: "youtube",
    video_id: "RmF4DKhPaV4",
    source_url: "https://youtu.be/RmF4DKhPaV4?si=9xSSQGAZ5btpUV5D",
    thumbnail: "https://img.youtube.com/vi/RmF4DKhPaV4/hqdefault.jpg",
    order: 13,
  },
  {
    id: "film-T2_rOujU3Yo",
    title: "NIVEA HANDCREAM_FESTIVALS",
    provider: "youtube",
    video_id: "T2_rOujU3Yo",
    source_url: "https://youtu.be/T2_rOujU3Yo?si=zNMlRJAsGfukzZlR",
    thumbnail: "https://img.youtube.com/vi/T2_rOujU3Yo/hqdefault.jpg",
    order: 14,
  },
  {
    id: "film-PutEWHRJq-o",
    title: "YERA GLASSWARE",
    provider: "youtube",
    video_id: "PutEWHRJq-o",
    source_url: "https://youtu.be/PutEWHRJq-o?si=w9Iv_UfE_vGEUQtT",
    thumbnail: "https://img.youtube.com/vi/PutEWHRJq-o/hqdefault.jpg",
    order: 15,
  },
  {
    id: "film-dIfpSHWzHA0",
    title: "STANDARD CHARTERED_MUMBAI MARATHON",
    provider: "youtube",
    video_id: "dIfpSHWzHA0",
    source_url: "https://youtu.be/dIfpSHWzHA0?si=piRnAIJ8ZKwGNmii",
    thumbnail: "https://img.youtube.com/vi/dIfpSHWzHA0/hqdefault.jpg",
    order: 16,
  },
  {
    id: "film-QOR0WAJmNEo",
    title: "OREO_LEMON TWIST",
    provider: "youtube",
    video_id: "QOR0WAJmNEo",
    source_url: "https://youtu.be/QOR0WAJmNEo?si=B1DoFzGOYyP6GfuQ",
    thumbnail: "https://img.youtube.com/vi/QOR0WAJmNEo/hqdefault.jpg",
    order: 17,
  },
  {
    id: "film-65sCFhbw0Uo",
    title: "HERO XPULSE_LONG ROAD",
    provider: "youtube",
    video_id: "65sCFhbw0Uo",
    source_url: "https://youtu.be/65sCFhbw0Uo?si=273jtzDuw6u5rTBB",
    thumbnail: "https://img.youtube.com/vi/65sCFhbw0Uo/hqdefault.jpg",
    order: 18,
  },
  {
    id: "film-F3CUIMwiBow",
    title: "HERO XPULSE_SOCIAL NETWORK",
    provider: "youtube",
    video_id: "F3CUIMwiBow",
    source_url: "https://youtu.be/F3CUIMwiBow?si=Dy5_g7CTfHjijcow",
    thumbnail: "https://img.youtube.com/vi/F3CUIMwiBow/hqdefault.jpg",
    order: 19,
  },
  {
    id: "film-jHA0F_J0JgA",
    title: "HERO XPULSE_ ADV",
    provider: "youtube",
    video_id: "jHA0F_J0JgA",
    source_url: "https://youtu.be/jHA0F_J0JgA?si=zIKJjejoy_qVI-UW",
    thumbnail: "https://img.youtube.com/vi/jHA0F_J0JgA/hqdefault.jpg",
    order: 20,
  },
  {
    id: "film-iMMX66AjjiY",
    title: "TATA AIA_ROHIN",
    provider: "youtube",
    video_id: "iMMX66AjjiY",
    source_url: "https://youtu.be/iMMX66AjjiY?si=5wq9UCq7OfXRDbpb",
    thumbnail: "https://img.youtube.com/vi/iMMX66AjjiY/hqdefault.jpg",
    order: 21,
  },
  {
    id: "film-5-sUXxrTFS0",
    title: "TATA AIA_HARJEET SETHI",
    provider: "youtube",
    video_id: "5-sUXxrTFS0",
    source_url: "https://youtu.be/5-sUXxrTFS0?si=FvULG8vtAAS1Brf4",
    thumbnail: "https://img.youtube.com/vi/5-sUXxrTFS0/hqdefault.jpg",
    order: 22,
  },
  {
    id: "film-aStnGho2NgA",
    title: "TATA AIA_ANAHITA",
    provider: "youtube",
    video_id: "aStnGho2NgA",
    source_url: "https://youtu.be/aStnGho2NgA?si=Q4Gg6ueoOcrbpjEq",
    thumbnail: "https://img.youtube.com/vi/aStnGho2NgA/hqdefault.jpg",
    order: 23,
  },
  {
    id: "film-hMvshSiTwBs",
    title: "STARPLUS_NAYISOCH AJINKYA",
    provider: "youtube",
    video_id: "hMvshSiTwBs",
    source_url: "https://youtu.be/hMvshSiTwBs?si=0y112kGBYTHh6J2T",
    thumbnail: "https://img.youtube.com/vi/hMvshSiTwBs/hqdefault.jpg",
    order: 24,
  },
  {
    id: "film-hwRA0K0d2To",
    title: "PRO KABADDI LEAGUE",
    provider: "youtube",
    video_id: "hwRA0K0d2To",
    source_url: "https://youtu.be/hwRA0K0d2To?si=XepnNw2TlbecpYzk",
    thumbnail: "https://img.youtube.com/vi/hwRA0K0d2To/hqdefault.jpg",
    order: 25,
  },
  {
    id: "film-DpGqisB7hE0",
    title: "ANANTHAAL_INAYAT",
    provider: "youtube",
    video_id: "DpGqisB7hE0",
    source_url: "https://youtu.be/DpGqisB7hE0?si=sc1sFdqXp69soDPN",
    thumbnail: "https://img.youtube.com/vi/DpGqisB7hE0/hqdefault.jpg",
    order: 26,
  },
  {
    id: "film-ut6ckJaGOYU",
    title: "FINDING A VOICE",
    provider: "youtube",
    video_id: "ut6ckJaGOYU",
    source_url: "https://youtu.be/ut6ckJaGOYU?si=ou3ionJaj_ADOuu6",
    thumbnail: "https://img.youtube.com/vi/ut6ckJaGOYU/hqdefault.jpg",
    order: 27,
  },
];
